const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Docena de Tequeños congelados (precio detal)",
      price: 800,
      image: require("./imagenes/tequeBlack.PNG"),
      category: "congelados",
      img1: "" /* aca se coloca imagen po dafault puede serv cagradas de internet 
                ej; "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-Pine-Green/Images/Nike-Dunk-Low-Off-White-Pine-Green/Lv2/img", 
                pero en el componente prodcutoItem se coloca en img; <img src={image.default} alt={title} />
                POR LOS MOENTOS USARE LA IMAGEN LOCAL PO LO QUE EN EL COMPONENTE SOLO COLOCO; <img src={image} alt={title} />*/,
      img2: "",
      cantidad: 1,
    },
    {
      id: 2,
      title: "Docena de Tequeños congelados (precio al mayor)",
      price: 650,
      image: require("./imagenes/tequeHeladera.png"),
      category: "congelados",
      img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-Pine-Green/Images/Nike-Dunk-Low-Off-White-Pine-Green/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Docena de Tequeños fritos + rica salsa de ajo",
      price: 1500,
      image: require("./imagenes/tequeSalsa.PNG"),
      category: "teque_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325289&w=1000",
      cantidad: 1,
    },
    {
      id: 4,
      title:
        "Combo fiestero Junior; Cincuanta 50 Tequeños fritos + rica salsa de ajo",
      price: 6250,
      image: require("./imagenes/tequeMonton.png"),
      category: "teque_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 5,
      title:
        "Combo fiestero Sennior; Cien 100 Tequeños fritos + rica salsa de ajo",
      price: 12500,
      image: require("./imagenes/tequeMonton.png"),
      category: "teque_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 6,
      title: "Combo 2 piezas de pollo rostizados + papas fritas + salsa BBQ",
      price: 12500,
      image: require("./imagenes/2piezas_papas.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 7,
      title: "Combo 4 piezas de pollo rostizados + papas fritas + salsa BBQ",
      price: 12500,
      image: require("./imagenes/4piezas_papas.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 8,
      title: "Combo 4 piezas de pollo rostizados + arepitas fritas + salsa BBQ",
      price: 12500,
      image: require("./imagenes/4piezas_arepas.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 9,
      title: "Combo 8 piezas de pollo rostizados + papas fritas + salsa BBQ",
      price: 12500,
      image: require("./imagenes/8piezas_papas.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 10,
      title: "Combo 4 alitas de pollo rostizados + papas fritas + salsa BBQ",
      price: 12500,
      image: require("./imagenes/4alitas_papas.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 11,
      title: "Combo 4 alitas de pollo rostizados + arepitas fritas + salsa BBQ",
      price: 12500,
      image: require("./imagenes/4alitas_arepas.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 12,
      title: "Milanesa a la napolitana + papas fritas",
      price: 12500,
      image: require("./imagenes/milaNapo.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 13,
      title: "Milanesa a caballo + papas fritas",
      price: 12500,
      image: require("./imagenes/milaCaballo.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
    {
      id: 14,
      title: "Milanesa de carne + papas fritas",
      price: 12500,
      image: require("./imagenes/mila.png"),
      category: "pollo_cocidos",
      img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
      img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
      cantidad: 1,
    },
  ],
};

export default data;
